### ISSUE TITLE
workflow confirmation

### ISSUE THREAD

**Issue by kylixfinance** [Kylix-Finance/kylix-finance-substrate#108]
We have to confirm the logic of this workflow is correct and if yes we have to apply it
![Image](https://github.com/user-attachments/assets/11012073-dc42-4d4c-9af3-ac1e15794791)
an example with numbers:
![Image](https://github.com/user-attachments/assets/168e7b39-3c6d-4cce-92e4-2272a73b5d1d)

file [source](https://viewer.diagrams.net/index.html?tags=%7B%7D&lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1#R%3Cmxfile%3E%3Cdiagram%20name%3D%22Page-1%22%20id%3D%22ceQuCCaNEiZvxDpdNKYI%22%3E5Vztb6M2GP9rIm2TWgEmED6maXa7KbdGzW13vS%2BTC77giWBEnCa5v342mFeTHm3T2GkrtYEHY8zz8nvenA7AZLX7kMIk%2FEQCFA0sI9gNwPXAYj8jm31wyj6nuADkhGWKg5xkVoQF%2FoEE0RDUDQ7QujGQEhJRnDSJPolj5NMGDaYp2TaHfSdR86kJXCKJsPBhJFO%2F4ICGOXU0NCr6Hwgvw%2BLJpiGurGAxWBDWIQzItkYC0wGYpITQ%2FGi1m6CIM6%2FgS37f7weulgtLUUz73PDP3cfJt6%2FxZBL%2Bayzux3%2Fuvn36cTEUa6P74oVRwN5fnJKUhmRJYhhNK%2BpVSjZxgPisBjurxswISRjRZMT%2FEKV7IUy4oYSRQrqKxFV55eJl1mST%2BuiR5RYaANMloo%2BMs%2FJx%2FF1qDxB8%2BYDICtF0zwakKIIUPzRlDYXKLMtxFVfZgWDsE5hc6PJpuYx2mH7lt18Oxdld7cr1TsycneyLk5i9b%2B0mfnpXv1bdlp0V971Aon1F6mklUst6m4bjaMVlMe8DjDbiSYu%2F5%2FPZHX%2BW7w8sJ2LvcnWfsqMlP%2FoFsisRXlP2Qb7zUSvGcvqrJKumJLYhpmiRwIyDW%2BbHenL9AaUU7R7lk7jqCAQQTrD0btvKpZiFnwib7uS1WOsqwaQCX8wGulRgc3x8GanCl%2BzWcZrCfW1AQnBM17WZ55xQKYprNjXFdYctUeczVoIvl%2FYCMFPin54vU6unSAvZa4JmloRmk5vZbPx5ejuePR3RpJExyQbF0b54iAa4N9QO%2BIAkhfUmSTjT2hyFPsUkVs7DC8ttMtFRzkNbqe8wLm1n1PQfBssqH%2Fcg2dkcpZhxAKUvdiugLwRphUCOpPtbTMMghdvz0X4NIMST2Di%2FuZmpZ5WIFUqc6AAK4HVwygKvFmXKPk8JdJxHKtwXU44OKt2xaGlVQp%2BA1VKT%2FI3EXfXKU2siYB1QzGKi%2FJWliZ4aPLcXPDROEDybcpL6OcTrKhTzQxgzQTHBhvxvEW2ISI5PH5cXE0IiyUCY%2BdOmPsMIL2N27DMd487sioME9mE0FhdWOAgy0%2BlCnaY5HQF4vG6213HH6YAd79VQR0lVUwFg9I1CNCuHyiH4LUpgGYEH%2BKFMagLkpwiuK%2FO5J7yoz%2BT0mAEZMOYDNmtmHFli1ciZ2KJrj1Dutr1WjgSUxzelAr712pB9nvZjS%2FZzlVlFlwHh%2BN0ZkAYZQlF56hsUdAklK%2Fecc1jgjFp1iw65nDQusGTHkzMex8s5Yz%2FX9YxsjGe8IueTiNkzSiGf%2BTf2a1yyDNq44AOyp1VikwxPTqg1tR7TsFvhm9WRNrpdaWM7HzieoJQUmJ7vSCy3pyMpfLsmnsRSEyifRTYOnL4ytfWSqfNWbQfoxWdXciZZao%2FRunQj5WYghfjecsKmbSiPjqyREtg5eX5h963oHR9Cntd8Bi1d8ZxTdJ%2B98wKsgkk%2FlWohfk0Aq1h3DbAaAW4NsqRotpaf5MOAoWk467j64R2QS8SHes6M%2FepdBosLW0wsCQqZaCl1Glo0nXtvf3X1Qh457z7cd%2Fa0NAAdUEQu%2B2W7IT9OFz9B76ub29ubL9PrHuj9gjqGdCt8gDiC9xFqLi%2Brn%2FAVCKKrqyu5GNpNJRh1oOCJG%2BpgKCmBElg8ixS%2Bf2p59G3PBxrUrVKbOWyjRe%2BWut1sqVe6eeyeenvJjneCnADIO5XeW1PdNA8wXln5HKjdMn66yl%2FfLeOaVXOB3HRq9NUrFw7Uh1heO0%2BzOtoOp46wlFQiFNSl%2BlYwNFPwYt0HG9%2BVhjsaargGOYQtVyLeX1%2FaNVqCGXUI5qSe1bYksRxoTOcZVNWL5kdJin1Uz6tqxHPuS7e%2BNGe6HfsHwKgr%2FXq1xrSt%2BJsPTQ9hvaKLOM%2BthbbanZ%2BmfvLRqwdhy5XAxd1fk%2FPzIcBrZ2f9XMgzCkPstPonEXmCXf2rDTD9Hw%3D%3D%3C%2Fdiagram%3E%3C%2Fmxfile%3E#%7B%22pageId%22%3A%22ceQuCCaNEiZvxDpdNKYI%22%7D)

**Comment by k-gunjan** [comment]
implemented the flow as per [features](https://docs.google.com/spreadsheets/d/1RdYHowje8s5WaxwP3yWYTFLjkvJphiT67iIbZnkwTzU/edit?gid=1464282055#gid=1464282055)
